version: '3.3'
services:
  db:
    image: mysql:8.0.25
    container_name: mysql
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 5rEF5r
      MYSQL_USER: spring
      MYSQL_PASSWORD: 5rEF5r
      MYSQL_DATABASE: rest_with_spring_boot_udemy
    ports:
      - "3308:3306"
    networks:
      - udemy-network

  rest-with-spring-boot-udemy:
    image: oakanderson/rest-with-spring-boot-udemy
    container_name: rest-with-spring-boot-udemy
    restart: always
    working_dir: /RestWithSpringBootUdemy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIROMENT: Production
    ports:
    - "8080:8080"
    command: mvn spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - udemy-network
networks:
  udemy-network:
    driver: bridge

