version: '3.3'
services:
  rest-with-spring-boot-udemy:
    image: rest-with-spring-boot-udemy
    container_name: rest-with-spring-boot-udemy
    restart: always
    working_dir: /RestWithSpringBootUdemy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIROMENT: Production
    ports:
    - "8080:8080"
    command: mvn spring-boot:run
networks:
  udemy-network:
    driver: bridge

